services:
  sqlserver:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123654MyPassword!
  moviedg.web:
    container_name: MoviesDGContainer
    ports:
      - "8001:80"
    image: ${DOCKER_REGISTRY-}moviedgweb
    build:
      context: .
      dockerfile: MovieDG.Web/Dockerfile
    depends_on:
      - sqlserver